"use client";

import { Amplify } from "aws-amplify";
import { LocaleProvider } from "@/lib/i18n";
import { GroupsProvider } from "@/lib/groups";
import { LanguageGate } from "@/components/i18n/language-gate";

try {
  // Generated by `ampx sandbox` / hosting deploy. Absent in CI or
  // pre-backend checkouts — pages then run on local demo data.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const outputs = require("../amplify_outputs.json");
  Amplify.configure(outputs);
} catch {
  // no backend configured; demo-data mode
}

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <LocaleProvider>
      <GroupsProvider>
        <LanguageGate />
        {children}
      </GroupsProvider>
    </LocaleProvider>
  );
}
